# fly.toml app configuration file generated for lm-vite-sparkling-meadow-807 on 2023-11-20T20:22:06-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lm-vite-sparkling-meadow-807"
primary_region = "bog"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
