# fly.toml app configuration file generated for lightmatter on 2023-11-26T17:58:16-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lightmatter"
primary_region = "bog"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
